### PR TITLE
Fix recording API not returning timestamp and returning 0 instead (#7079).

### LINKED ISSUE #7079: Recording API gives 0 as time stamp in message field
### Short description
The [recording API](https://antmedia.io/rest/#/default/enableRecording) gives the correct response, but the time stamp is 0 in the message field in v2.13. While in v2.12.0 the response had the time stamp as the message.

### Environment

* Ant Media Server version: v2.13

### Steps to reproduce
1. Start publishing the stream
2. Call the recording API
3. Check the response

### Expected behavior

The response should contain the timestamp in the message field.

```
{
    “success”: true,
    “message”: “1740419093306”,
    “dataId”: “kWIA47U2aEt05TmBcHwK7Ozv”,
    “errorId”: 0
}
```

### Actual behavior

In v2.13, the response is 200, but the message field does not contain the time stamp of recording.

{
    "success": true,
    "message": "0",
    "dataId": "uMtFQYZcsb9PnKvBRcVYMw6p",
    "errorId": 0
}

### PR DESCRIPTION
**Pull request by LaCrak27**
Fixes #7079 

## Proposed Changes

  - Recording API gives the created muxer a timestamp of the start of the recording, and also returns it in the API message.

### CODE REVIEW

File: src/main/java/io/antmedia/muxer/MuxAdaptor.java [hunk 1]
```diff
@@ -2266,6 +2269,9 @@ else if(recordType == RecordType.WEBM) {
 			logger.error("Unrecognized record type: {}", recordType);
 		}
 
+		LocalDateTime ldt = LocalDateTime.now();
```
Comment (mekya) [inline src/main/java/io/antmedia/muxer/MuxAdaptor.java:2272]: Hi @LaCrak27 ,
Thank you for the fix and contribution

It may throw Nullpointer Exception, I'll just slightly change [the place of this lines](https://github.com/ant-media/Ant-Media-Server/blob/master/src/main/java/io/antmedia/muxer/Muxer.java#L734) to make it work in all cases



Regards
