### PR TITLE
Fix/same rtmp url

### LINKED ISSUE #3284: Add checkpoint if rtmp-endpoint is already added to broadcast in REST API.
Add checkpoint if rtmp-endpoint is already added to broadcast in REST API.

Current issue:
We are able to add multiple times the same RTMP Endpoint but this shouldn't be possible. It should give an error.

### PR DESCRIPTION
**Pull request by eneskuluk**
# Pull Request
This PR fixes #3284
This PR improves addEndpointV3 function. It adds ability to check whether same RTMP url was already added for specified broadcast.
Also improves unit test of the addEndpointV3 function. It was done by adding same RTMP urls to test but after changes, some of the tests should return false instead of true since we are checking whether it has the same RTMP url or not. Also added 2 checks for same RTMP urls.

### CODE REVIEW

File: src/main/java/io/antmedia/rest/BroadcastRestService.java [hunk 1]
```diff
@@ -343,8 +343,8 @@ public Result addEndpointV3(@ApiParam(value = "Broadcast id", required = true) @
 		
 		String rtmpUrl = null;
 		Result result = new Result(false);
-		
-		if(endpoint != null && endpoint.getRtmpUrl() != null) {
+		List<Endpoint> endpoints = getDataStore().get(id) != null ? getDataStore().get(id).getEndPointList():null;
```
Comment (mekya) [inline src/main/java/io/antmedia/rest/BroadcastRestService.java:346]: Don't query the database twice

**Review by mekya — APPROVED** [review]
