### PR TITLE
Accept only GET requests for HTTP token

### LINKED ISSUE #3291: Add more security restriction for request types(POST) to token mechanism
### Short description
Anyone can access MP4 records using POST requests when the JWT token mechanism enabled.

### Steps to reproduce
1. Enable Play One-Time token, Hash-based or JWT token filters.
2. Request `http://localhost:5080/LiveApp/streams/stream1.mp4` with POST request type.

### Expected behavior
It shouldn't access directly if token mechanism enabled.

### Actual behavior
Anyone access MP4 records.

### PR DESCRIPTION
**Pull request by SelimEmre**
# Pull Request

This PR fixes #3291

Changes proposed in this pull request:
- Add tests for `HTTP POST` token requests
- Add token filter check to inside of `GET` function

### CODE REVIEW

File: src/main/java/io/antmedia/filter/TokenFilterManager.java [hunk 1]
```diff
@@ -144,11 +144,8 @@ public void doFilter(ServletRequest request, ServletResponse response, FilterCha
 					return;
 				}
 			}
-			
+			chain.doFilter(request, response);	
 		}
-	
-		chain.doFilter(request, response);
```
Comment (mekya) [inline src/main/java/io/antmedia/filter/TokenFilterManager.java:150]: I think you need to return error if the request method is not "GET"

**Review by mekya — CHANGES_REQUESTED** [review]

**Review by mekya — APPROVED** [review]
